### ISSUE TITLE
sendto failed: EPIPE (Broken pipe)

### ISSUE THREAD

**Issue by alvintchui** [alexbbb/android-upload-service#32] opened 2015-06-09 14:05 UTC
Hi Alex,

I am experiencing a strange problem with the uploading service.
I use the library to upload images to a remote server but the uploading service seems unreliable.

In my test, the uploading service is triggered by a button click. Sometimes the uploading service goes well.

But sometime it returns an error message (captured below). 
I tried to click the "upload" button again when the first upload failed, most of the time, the upload will be successful in the second time.

Am I not missing any configuration?

Error Message
06-09 21:48:53.613  17985-17985/com.rick.er E/er﹕ Error in upload with ID: 782f1e16-9a1b-4448-b862-7f8eb7867b5a. sendto failed: EPIPE (Broken pipe)
    java.net.SocketException: sendto failed: EPIPE (Broken pipe)
            at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:550)
            at libcore.io.IoBridge.sendto(IoBridge.java:519)
            at java.net.PlainSocketImpl.write(PlainSocketImpl.java:511)
            at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:46)
            at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:269)
            at libcore.net.http.ChunkedOutputStream.writeHex(ChunkedOutputStream.java:102)
            at libcore.net.http.ChunkedOutputStream.writeBufferedChunkToSocket(ChunkedOutputStream.java:128)
            at libcore.net.http.ChunkedOutputStream.close(ChunkedOutputStream.java:118)
            at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:812)
            at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:293)
            at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:505)
            at androidUpload.src.com.alexbbb.uploadservice.UploadService.handleFileUpload(UploadService.java:172)
            at androidUpload.src.com.alexbbb.uploadservice.UploadService.onHandleIntent(UploadService.java:138)
            at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:153)
            at android.os.HandlerThread.run(HandlerThread.java:60)
     Caused by: libcore.io.ErrnoException: sendto failed: EPIPE (Broken pipe)
            at libcore.io.Posix.sendtoBytes(Native Method)
            at libcore.io.Posix.sendto(Posix.java:151)
            at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:177)
            at libcore.io.IoBridge.sendto(IoBridge.java:517)
            at java.net.PlainSocketImpl.write(PlainSocketImpl.java:511)
            at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:46)
            at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:269)
            at libcore.net.http.ChunkedOutputStream.writeHex(ChunkedOutputStream.java:102)
            at libcore.net.http.ChunkedOutputStream.writeBufferedChunkToSocket(ChunkedOutputStream.java:128)
            at libcore.net.http.ChunkedOutputStream.close(ChunkedOutputStream.java:118)
            at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:812)
            at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:293)
            at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:505)
            at androidUpload.src.com.alexbbb.uploadservice.UploadService.handleFileUpload(UploadService.java:172)
            at androidUpload.src.com.alexbbb.uploadservice.UploadService.onHandleIntent(UploadService.java:138)
            at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:153)
            at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by alexbbb** [comment] 2015-07-14 10:31
This issue is a duplicate of #27 
I'm closing this issue. Please refer to the other one

**Closed by alexbbb** 2015-07-14 10:31 UTC
Labels: duplicate
