### ISSUE TITLE
Catching strange compile error

### ISSUE THREAD

**Issue by neilyoung** [alexbbb/android-upload-service#81] opened 2016-01-17 18:11 UTC
When I just include your dependency into my gradle project I'm catching this

    Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.

Any other requirements to be met?

**Comment by neilyoung** [comment] 2016-01-17 18:20
Some more info on that. I'm using 

    compile 'com.android.support:appcompat-v7:21.0.0'          

The error is:

    /Users/myUserName/StudioProjects/MyProject/myProject/build/intermediates/exploded-aar/com.android.support/appcompat-v7/23.1.1/res/values-v23/values-v23.xml
    Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
    Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.
    Error:Execution failed for task ':myProject:processDebugResources'.
    > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/myUserName/android-sdk-mac_x86/build-tools/21.0.1/aapt'' finished with non-zero exit value 1

**Comment by alexbbb** [comment] 2016-01-17 18:33
That error is something in your project, which is not related to Android Upload Service.

**Comment by neilyoung** [comment] 2016-01-17 18:51
No, it is not. If I remove your dependency, the error is gone. Thanks

**Comment by alexbbb** [comment] 2016-01-17 18:59
The only cause of this error is a mismatch in Android support libraries version. Android Upload Service uses v.23.1.1 and in your project you're using v.21. Update your project to the last version or check the solution in #75

**Comment by neilyoung** [comment] 2016-01-17 19:01
Yes, indeed, this is the problem. Unfortunately I cannot upgrade to 23, because the permission model has changed and right now there is no time to change it all. 

So it seems I can't use your library

**Comment by alexbbb** [comment] 2016-01-17 19:04
Support library is used only for notifications compatibility. You can use
v.21 too. Try the solution posted in #75 and change the version to 21. It
should work.
Il 17 gen 2016 8:01 PM, "neilyoung" <notifications@github.com> ha scritto:

**Comment by neilyoung** [comment] 2016-01-17 19:29
No, sorry. This doesn't work for me. I admit your library works with a brand new project. But unfortunately the world is mostly legacy.

**Comment by neilyoung** [comment] 2016-01-17 19:36
I tried a lot. This should work. But it doesn't...

apply plugin: 'com.android.application'

android {
    compileSdkVersion 'Google Inc.:Google APIs:22'
    buildToolsVersion "22.0.1"

    defaultConfig {
        applicationId "com.MyProject.myProject"
        minSdkVersion 22
        targetSdkVersion 22

    }
    configurations.all {
        resolutionStrategy {
            force 'com.android.support:support-v4:23.1.1'
            force 'com.android.support:appcompat-v7:23.1.1'
        }
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-project.txt'
        }
    }

    dexOptions {
        preDexLibraries true
    }


}

dependencies {

    compile project(':supertooltip')
    compile project(':navizonLocation')
    compile 'com.google.code.gson:gson:2.3'
    compile 'com.google.protobuf:protobuf-java:2.4.1'
    compile 'com.google.maps.android:android-maps-utils:0.4+'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.google.android.gms:play-services:6+'
    compile files('libs/acra-4.5.0.jar')
    compile files('libs/universal-image-loader-1.9.1.jar')
    compile 'com.alexbbb:uploadservice:1.6'

}


Be sure, I have tried any other combination of target/build/minSDK. Nothing helps.

**Comment by alexbbb** [comment] 2016-01-17 19:54
compileSdkVersion should match the version of the support library and I know it's a good practice to always use the latest available build tools. In your case, have you tried something like this?
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 'Google Inc.:Google APIs:23'
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "com.MyProject.myProject"
        minSdkVersion 22
        targetSdkVersion 22

    }
    configurations.all {
        resolutionStrategy {
            force 'com.android.support:support-v4:23.1.1'
            force 'com.android.support:appcompat-v7:23.1.1'
        }
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-project.txt'
        }
    }

    dexOptions {
        preDexLibraries true
    }

}

dependencies {
    compile project(':supertooltip')
    compile 'com.google.code.gson:gson:2.3'
    compile 'com.google.protobuf:protobuf-java:2.4.1'
    compile 'com.google.maps.android:android-maps-utils:0.4+'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.google.android.gms:play-services:6+'
    compile files('libs/acra-4.5.0.jar')
    compile files('libs/universal-image-loader-1.9.1.jar')
    compile 'com.alexbbb:uploadservice:1.6'
}
```

**Comment by neilyoung** [comment] 2016-01-17 20:09
I'm sure this issue is caused by Google Play Services lib...

**Comment by alexbbb** [comment] 2016-01-17 20:27
I've been able to reproduce exacly the issue you got with a project from scratch and I've documented the solution here: https://github.com/alexbbb/android-upload-service/wiki/Setup
Ignore the initial setup instructions which are for the upcoming 2.0 release and check the troubleshooting section. I've also tried to reproduce your error by adding

    compile 'com.google.code.gson:gson:2.3'
    compile 'com.google.protobuf:protobuf-java:2.4.1'
    compile 'com.google.maps.android:android-maps-utils:0.4+'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.google.android.gms:play-services:6+'

into the `dependencies` section of the app with which I've reproduced your error, but after adding the `configurations.all` instruction, everything works. I suspect that the dependency issue could be somewhere in those dependencies you have:
```
compile project(':supertooltip')
compile files('libs/acra-4.5.0.jar')
compile files('libs/universal-image-loader-1.9.1.jar')
```

**Comment by neilyoung** [comment] 2016-01-18 08:11
No, I'm sorry to disappoint you. This doesn't work for me. But the error is different now:

Error:(131) Attribute "theme" has already been defined

File is ../build/intermediates/res/merged/debug/values/values.xml

**Comment by neilyoung** [comment] 2016-01-18 08:23
...and after falling back to gradle 1.2.3 

../build/intermediates/exploded-aar/com.google.android.gms/play-services/4.4.52/res/values/wallet_colors.xml

My project is completely fucked up now :(

**Comment by neilyoung** [comment] 2016-01-18 08:34
Good news. I could recover from the latest error by replacing 

    compile 'com.google.android.gms:play-services:4+'

by

    compile 'com.google.android.gms:play-services:6.1.11'

And then your suggested fix did work. Thanks for your efforts

**Comment by alexbbb** [comment] 2016-01-18 09:45
@neilyoung managing dependencies is not easy and the mess is always around the corner. Every time a new tool comes around, they promise us it will be the best thing since sliced bread, but as we know, it's never easy like that :) Glad that you've found the solution. I'm closing this ticket.

**Closed by alexbbb** 2016-01-18 09:45 UTC
Labels: support

**Comment by neilyoung** [comment] 2016-01-18 10:03
You say it :) I hope I will have more fun using your component. But if not: I know you as a smart and responsive person now :))

Thanks again

**Comment by neilyoung** [comment] 2016-01-18 10:57
Works perfectly, btw. Thanks for convincing me to not give up :)

Regards

**Comment by alexbbb** [comment] 2016-01-18 11:16
You're welcome :+1:

**Comment by neilyoung** [comment] 2016-01-18 12:08
BTW: After all I switched my toolchain to API 23 now, keeping targetSDKVersion 21. Everything works fine. By keeping the lower SDK target I'm not immediately forced to switch all to the new permissions model. The resolutionStrategy entry is of course not required anymore.
